window.SHOPS = [

  {
    id:0,
    type:"image",
    image:"shop1",
    src:"shop1.png",
    url:"https://www.iizuka-shotengai.com/dagasoft",
    messages:[
      "濃厚生乳ソフトクリーム専門店　だがソフへようこそ！",
      "たくさんの種類のアレンジソフトクリームをご用意しています。",
      "小さなお子様も一緒にゆっくり滞在していただけるよう、",
      "絵本やおもちゃ等も設置しています。",
      "ぜひ当店で「のんびり」とおすごしください！"
    ]
  },

  {
    id:1,
    type:"image",
    image:"shop2",
    src:"shop2.png",
    url:"https://www.iizuka-shotengai.com",
    messages:[
      "ようこそ起こしなされた！",
      "私は、後ろの駄菓子屋の店主でござる！",
      "飯塚宿の紹介を少し",
      "飯塚宿は、長崎街道の宿場として大いに栄えし町にござる。",
      "異国渡りの砂糖が運ばれ、",
      "「シュガーロード」と呼ばれる菓子文化の道としても知られ、",
      "甘味文化が花開いた地でござる！",
      "今なお、その賑わいの名残は商店街に息づいておりまする。",
      "それでは、",
      "商店街のお店をご案内つかまつる！"
    ]
  },

  {
    id:2,
    type:"image",
    image:"shop3",
    src:"shop3.png",
    url:"https://www.iizuka-shotengai.com/dagasystem",
    messages:[
      "おっ！駄菓子屋さん！",
      "うちのお店をはじめて発見されたお客様は、",
      "ちょっとだけテンションあがります⤴",
      "見るだけでもいいので、よっていって！"
    ]
  },

  {
    id:3,
    type:"image",
    image:"shop4",
    src:"shop4.png",
    url:"https://www.iizuka-shotengai.com/taiyaki",
    messages:[
      "どうしても、たい焼きにあんこを入れすぎるとよね～",
      "・・・・・・・",
      "まっ、いっか！",
      "お客さん喜んどんしゃあきね！",
      "さぁ食べていきんしゃい！！"
    ]
  },

  {
    id:4,
    type:"image",
    image:"shop5",
    src:"shop5.png",
    url:"https://www.iizuka-shotengai.com/kurakake",
    messages:[
      "お米はご注文いただいて精米しますので、お米の鮮度が違います！",
      "豆類の品ぞろえは福岡県内トップクラスです！",
      "ぜひお立ち寄りください！"
    ]
  },

  {
    id:5,
    type:"video",
    image:"movie6",
    src:"cookie.mp4",
    url:"https://www.iizuka-shotengai.com/dagasoft",
    messages:[]
  },

  {
    id:6,
    type:"image",
    image:"shop7",
    src:"shop7.png",
    url:"https://www.iizuka-shotengai.com/kurakake",
    messages:[
      "お米はご注文いただいて精米しますので、お米の鮮度が違います！",
      "豆類の品ぞろえは福岡県内トップクラスです！",
      "ぜひお立ち寄りください！"
    ]
  },

  {
    id:7,
    type:"image",
    image:"shop8",
    src:"shop8.png",
    url:"https://example.com/8",
    messages:[
      "shop8へようこそ！",
      "限定商品あります！",
      "ぜひご覧ください！"
    ]
  },

  {
    id:8,
    type:"image",
    image:"shop9",
    src:"shop9.png",
    url:"https://example.com/9",
    messages:[
      "shop9へようこそ！",
      "本日営業中！",
      "ぜひどうぞ！"
    ]
  },

  {
    id:9,
    type:"image",
    image:"shop10",
    src:"shop10.png",
    url:"https://example.com/10",
    messages:[
      "shop10へようこそ！",
      "人気急上昇中！",
      "ぜひ見ていってね！"
    ]
  },

  {
    id:10,
    type:"image",
    image:"shop11",
    src:"shop11.png",
    url:"https://www.iizuka-shotengai.com/taiyaki",
    messages:[
      "たい焼き発見！",
      "あんこ、入れすぎてます！！",
      "超人気店です！",
      "ぜひどうぞ！"
    ]
  },

  {
    id:11,
    type:"image",
    image:"shop12",
    src:"shop12.png",
    url:"https://example.com/12",
    messages:[
      "shop12へようこそ！",
      "焼きたてです！",
      "ぜひ食べてみて！"
    ]
  },

  {
    id:12,
    type:"image",
    image:"shop13",
    src:"shop13.png",
    url:"https://example.com/13",
    messages:[
      "shop13へようこそ！",
      "かわいい雑貨あります！",
      "ぜひ見ていってね！"
    ]
  },

  {
    id:13,
    type:"image",
    image:"shop14",
    src:"shop14.png",
    url:"https://example.com/14",
    messages:[
      "shop14へようこそ！",
      "本日のおすすめ！",
      "ぜひどうぞ！"
    ]
  },

  {
    id:14,
    type:"image",
    image:"shop15",
    src:"shop15.png",
    url:"https://example.com/15",
    messages:[
      "shop15へようこそ！",
      "人気商品あります！",
      "チェックしてね！"
    ]
  },

  {
    id:15,
    type:"image",
    image:"shop16",
    src:"shop16.png",
    url:"https://example.com/16",
    messages:[
      "shop16へようこそ！",
      "営業中です！",
      "ぜひどうぞ！"
    ]
  },

  {
    id:16,
    type:"image",
    image:"shop17",
    src:"shop17.png",
    url:"https://example.com/17",
    messages:[
      "shop17へようこそ！",
      "おすすめあります！",
      "ぜひ見ていってね！"
    ]
  },

  {
    id:17,
    type:"image",
    image:"shop18",
    src:"shop18.png",
    url:"https://example.com/18",
    messages:[
      "shop18へようこそ！",
      "限定商品あります！",
      "チェックしてね！"
    ]
  },

  {
    id:18,
    type:"image",
    image:"shop19",
    src:"shop19.png",
    url:"https://example.com/19",
    messages:[
      "shop19へようこそ！",
      "商店街を楽しもう！",
      "ぜひどうぞ！"
    ]
  },

  {
    id:19,
    type:"image",
    image:"shop20",
    src:"shop20.png",
    url:"https://example.com/20",
    messages:[
      "shop20へようこそ！",
      "本日営業中！",
      "ぜひご来店ください！"
    ]
  },

  {
    id:20,
    type:"image",
    image:"shop21",
    src:"shop21.png",
    url:"https://example.com/21",
    messages:[
      "shop21へようこそ！",
      "おすすめあります！",
      "ぜひどうぞ！"
    ]
  },

  {
    id:21,
    type:"image",
    image:"shop22",
    src:"shop22.png",
    url:"https://example.com/22",
    messages:[
      "shop22へようこそ！",
      "人気商品あります！",
      "ぜひ見ていってね！"
    ]
  },

  {
    id:22,
    type:"image",
    image:"shop23",
    src:"shop23.png",
    url:"https://example.com/23",
    messages:[
      "shop23へようこそ！",
      "営業中です！",
      "ぜひどうぞ！"
    ]
  },

  {
    id:23,
    type:"image",
    image:"shop24",
    src:"shop24.png",
    url:"https://example.com/24",
    messages:[
      "shop24へようこそ！",
      "おすすめあります！",
      "チェックしてね！"
    ]
  },

  {
    id:24,
    type:"image",
    image:"shop25",
    src:"shop25.png",
    url:"https://example.com/25",
    messages:[
      "shop25へようこそ！",
      "限定商品あります！",
      "ぜひどうぞ！"
    ]
  },

  {
    id:25,
    type:"image",
    image:"shop26",
    src:"shop26.png",
    url:"https://example.com/26",
    messages:[
      "shop26へようこそ！",
      "人気スポットです！",
      "ぜひ見ていってね！"
    ]
  },

  {
    id:26,
    type:"image",
    image:"shop27",
    src:"shop27.png",
    url:"https://example.com/27",
    messages:[
      "shop27へようこそ！",
      "本日のおすすめ！",
      "ぜひどうぞ！"
    ]
  },

  {
    id:27,
    type:"image",
    image:"shop28",
    src:"shop28.png",
    url:"https://example.com/28",
    messages:[
      "shop28へようこそ！",
      "営業中です！",
      "ぜひ見ていってね！"
    ]
  },

  {
    id:28,
    type:"image",
    image:"shop29",
    src:"shop29.png",
    url:"https://example.com/29",
    messages:[
      "shop29へようこそ！",
      "人気商品あります！",
      "チェックしてね！"
    ]
  },

  {
    id:29,
    type:"image",
    image:"shop30",
    src:"shop30.png",
    url:"https://www.iizuka-shotengai.com",
    messages:[
      "ようこそ起こしなされた！",
      "私は、後ろの駄菓子屋の店主でござる！",
      "飯塚宿の紹介を少し",
      "飯塚宿は、長崎街道の宿場として大いに栄えし町にござる。",
      "異国渡りの砂糖が運ばれ、",
      "「シュガーロード」と呼ばれる菓子文化の道としても知られ、",
      "甘味文化が花開いた地でござる！",
      "今なお、その賑わいの名残は商店街に息づいておりまする。",
      "それでは、",
      "商店街のお店をご案内つかまつる！"
    ]
  }

];
